# .github/workflows/pr-build.yml

name: Build and Test on Pull Request

on:
  pull_request:
    types: [opened, synchronize]
    branches: [ main ]

jobs:
  run-tests-and-comment:
    environment: Dev
    runs-on: ubuntu-latest
    # Add permissions for the GITHUB_TOKEN
    permissions:
      pull-requests: write

    # services:
    #   mysql:
    #     image: mysql/mysql-server:8.0
    #     env:
    #       MYSQL_ROOT_PASSWORD: password
    #       MYSQL_DATABASE: testing
    #       MYSQL_USER: root
    #       MYSQL_PASSWORD: password
    #     ports:
    #       - 3307:3306
    #     options: --health-cmd="mysqladmin ping -uroot -ppassword" --health-interval=10s --health-timeout=5s --health-retries=10

    # env:
    #   DB_CONNECTION: mysql
    #   DB_HOST: mysql
    #   DB_PORT: 3306
    #   DB_DATABASE: testing
    #   DB_USERNAME: root
    #   DB_PASSWORD: password

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Find Previous Comment
        id: find-comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: ''

      - name: Delete Previous Comment
        if: steps.find-comment.outputs.comment-id != ''
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.deleteComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: ${{ steps.find-comment.outputs.comment-id }}
            })

      # laravel tests here
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'
      - name: Install Dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php -- --version=2.7.6
          sudo mv composer.phar /usr/local/bin/composer
          composer install --no-interaction --prefer-dist
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Start Sail
        run: |
          ./vendor/bin/sail up -d
      - name: Set Up Database
        run: |
          ./vendor/bin/sail artisan migrate --seed
      - name: Execute tests
        run: |
          ./vendor/bin/sail test > TEST_RESULTS

      - name: Load test results
        id: load_test_results
        run: |
          echo "results<<EOF" >> $GITHUB_OUTPUT
          cat TEST_RESULTS >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      

      # Create a new comment with the image details
      - name: Create New Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## PHPUnit Test Results

            **Result: ${{ steps.tests.outcome == 'success' && '✅' || '❌' }} ${{ steps.tests.outcome }}**

            <details>
            <summary>Click to see full test output</summary>

            ```
            ${{ steps.load_test_results.outputs.results }}
            ```
            </details>
