# .github/workflows/pr-build.yml

name: Build and Test on Pull Request

on:
  pull_request:
    types: [opened, synchronize]
    branches: [ master ]

jobs:
  build-and-comment:
    environment: Dev
    runs-on: ubuntu-latest
    # Add permissions for the GITHUB_TOKEN
    permissions:
      pull-requests: write

    strategy:
      matrix:
        php: [7.4, 7.3, 7.2]
        laravel: [6.*, 5.8.*, 5.7.*, 5.6.*, 5.5.*]
        dependency-version: [prefer-lowest, prefer-stable]
        os: [ubuntu-latest, windows-latest]
        include:
          - laravel: 6.*
            testbench: 4.*
          - laravel: 5.8.*
            testbench: 3.8.*
          - laravel: 5.7.*
            testbench: 3.7.*
          - laravel: 5.6.*
            testbench: 3.6.*
          - laravel: 5.5.*
            testbench: 3.5.*
        exclude:
            - laravel: 5.7.*
              php: 7.4
            - laravel: 5.6.*
              php: 7.4
            - laravel: 5.5.*
              php: 7.4

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Find Previous Comment
        id: find-comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: ''

      - name: Delete Previous Comment
        if: steps.find-comment.outputs.comment-id != ''
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.deleteComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: ${{ steps.find-comment.outputs.comment-id }}
            })

      # Create a new comment with the image details
      - name: Create New Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Test Comment Body
