# .github/workflows/pr-build.yml

name: Build and Test on Pull Request

on:
  pull_request:
    types: [opened, synchronize]
    branches: [ master ]

jobs:
  build-and-comment:
    environment: Dev
    runs-on: ubuntu-latest
    # Add permissions for the GITHUB_TOKEN
    permissions:
      pull-requests: write

    strategy:
      matrix:
        php: [8.2]
        laravel: [11.9.*]
        testbench: [9.*]
        dependency-version: [prefer-stable]
        os: [ubuntu-latest]

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Find Previous Comment
        id: find-comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: ''

      - name: Delete Previous Comment
        if: steps.find-comment.outputs.comment-id != ''
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.deleteComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: ${{ steps.find-comment.outputs.comment-id }}
            })

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      - name: Execute tests
        id: tests
        continue-on-error: true
        run: vendor/bin/phpunit > TEST_RESULTS

      - name: Load test results
        id: load_test_results
        run: |
          echo "results<<EOF" >> $GITHUB_OUTPUT
          cat TEST_RESULTS >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # Create a new comment with the image details
      - name: Create New Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## PHPUnit Test Results

            **Matrix:** `php: ${{ matrix.php }}`, `laravel: ${{ matrix.laravel }}`, `deps: ${{ matrix.dependency-version }}`
            **Result: ${{ steps.tests.outcome == 'success' && '✅' || '❌' }} ${{ steps.tests.outcome }}**

            <details>
            <summary>Click to see full test output</summary>

            ```
            ${{ steps.load_test_results.outputs.results }}
            ```
            </details>

      - name: Fail workflow if tests failed
        if: steps.tests.outcome == 'failure'
        run: exit 1
